"""Synthetic development corpus: 32 tasks, support docs plus distractors.

This is not PaperSearchQA and not a general benchmark. Biomedical items are
original short abstracts that state textbook facts. Computer-science items are
fictional papers for AutoTraining-style condition checks.
"""

from __future__ import annotations

from dataclasses import dataclass

from research_agent.grading.contracts import GradingSpec


@dataclass(frozen=True)
class DevTask:
    task_id: str
    question: str
    split: str
    spec: GradingSpec
    search_hint: str


def _doc(doc_id: str, title: str, paragraphs: list[str], source: str, **metadata: object) -> dict:
    return {
        "doc_id": doc_id,
        "title": title,
        "paragraphs": paragraphs,
        "source": source,
        "version": "synthetic-dev-v1",
        "metadata": {"synthetic": True, **metadata},
    }


DOCUMENTS: list[dict] = [
    _doc(
        "bio:rb1",
        "RB1 mutations in childhood retinoblastoma",
        [
            "Childhood retinoblastoma is associated with germline or somatic inactivation of the RB1 tumor suppressor gene.",
            "The RB1 protein regulates the G1 to S transition. Biallelic loss removes this checkpoint in retinal cells.",
        ],
        "synthetic-bio-001",
        domain="biomedical",
    ),
    _doc(
        "bio:brca1",
        "BRCA1 and hereditary breast cancer risk",
        [
            "Pathogenic BRCA1 variants raise lifetime risk of breast and ovarian cancer.",
            "BRCA1 participates in homologous recombination repair of double-strand DNA breaks.",
        ],
        "synthetic-bio-002",
        domain="biomedical",
    ),
    _doc(
        "bio:imatinib",
        "Imatinib for chronic myeloid leukemia",
        [
            "Imatinib inhibits the BCR-ABL tyrosine kinase produced by the t(9;22) Philadelphia chromosome.",
            "In newly diagnosed chronic-phase CML, imatinib produces high rates of complete cytogenetic response.",
        ],
        "synthetic-bio-003",
        domain="biomedical",
    ),
    _doc(
        "bio:insulin",
        "Pancreatic beta cells and insulin secretion",
        [
            "Insulin is secreted by pancreatic beta cells in the islets of Langerhans.",
            "Glucose uptake through GLUT2 raises ATP, closing K-ATP channels and triggering insulin granule release.",
        ],
        "synthetic-bio-004",
        domain="biomedical",
    ),
    _doc(
        "bio:crispr",
        "Cas9 nuclease in CRISPR genome editing",
        [
            "Streptococcus pyogenes Cas9 is an RNA-guided endonuclease that creates DNA double-strand breaks.",
            "A single-guide RNA directs Cas9 to a PAM-adjacent target sequence.",
        ],
        "synthetic-bio-005",
        domain="biomedical",
    ),
    _doc(
        "bio:tp53",
        "TP53 as a frequently mutated tumor suppressor",
        [
            "TP53 encodes the p53 transcription factor and is among the most commonly mutated genes in human cancers.",
            "p53 activates DNA-repair and apoptosis programs after cellular stress.",
        ],
        "synthetic-bio-006",
        domain="biomedical",
    ),
    _doc(
        "bio:metformin",
        "Metformin as first-line therapy in type 2 diabetes",
        [
            "Metformin is recommended as initial pharmacologic therapy for type 2 diabetes unless contraindicated.",
            "The drug reduces hepatic gluconeogenesis and improves peripheral insulin sensitivity.",
        ],
        "synthetic-bio-007",
        domain="biomedical",
    ),
    _doc(
        "bio:vegf",
        "Bevacizumab blocks VEGF-A angiogenesis",
        [
            "Bevacizumab is a monoclonal antibody that binds VEGF-A and inhibits tumor angiogenesis.",
            "VEGF-A signals through VEGFR-2 on endothelial cells.",
        ],
        "synthetic-bio-008",
        domain="biomedical",
    ),
    _doc(
        "bio:mhc1",
        "MHC class I antigen presentation to CD8 T cells",
        [
            "MHC class I molecules present cytosolic peptide antigens to CD8-positive cytotoxic T cells.",
            "TAP transporters move peptides from the cytosol into the endoplasmic reticulum for MHC I loading.",
        ],
        "synthetic-bio-009",
        domain="biomedical",
    ),
    _doc(
        "bio:atp",
        "Mitochondrial oxidative phosphorylation produces ATP",
        [
            "Most cellular ATP in aerobic eukaryotic cells is generated by mitochondrial oxidative phosphorylation.",
            "The electron transport chain pumps protons to drive ATP synthase.",
        ],
        "synthetic-bio-010",
        domain="biomedical",
    ),
    _doc(
        "bio:hemoglobin",
        "Iron in the heme group of hemoglobin",
        [
            "Each hemoglobin subunit binds one heme group that contains a ferrous iron atom.",
            "Oxygen binds reversibly to that iron in the lungs and is released in peripheral tissues.",
        ],
        "synthetic-bio-011",
        domain="biomedical",
    ),
    _doc(
        "bio:synapse",
        "Chemical synaptic transmission",
        [
            "At chemical synapses, the presynaptic terminal releases neurotransmitter vesicles into the synaptic cleft.",
            "Postsynaptic receptors convert the chemical signal into ion flow or second-messenger cascades.",
        ],
        "synthetic-bio-012",
        domain="biomedical",
    ),
    _doc(
        "bio:ace2",
        "ACE2 is the cellular receptor for SARS-CoV-2",
        [
            "SARS-CoV-2 spike protein binds angiotensin-converting enzyme 2 (ACE2) on host cells.",
            "ACE2 is expressed on airway epithelium and several extrapulmonary tissues.",
        ],
        "synthetic-bio-013",
        domain="biomedical",
    ),
    _doc(
        "bio:amyloid",
        "Amyloid-beta plaques in Alzheimer disease",
        [
            "Neuritic plaques in Alzheimer disease contain aggregated amyloid-beta peptides derived from APP.",
            "Amyloid-beta 42 is more aggregation-prone than amyloid-beta 40.",
        ],
        "synthetic-bio-014",
        domain="biomedical",
    ),
    _doc(
        "bio:dopamine",
        "Substantia nigra dopamine loss in Parkinson disease",
        [
            "Parkinson disease involves degeneration of dopaminergic neurons in the substantia nigra pars compacta.",
            "Striatal dopamine depletion produces bradykinesia, rigidity, and rest tremor.",
        ],
        "synthetic-bio-015",
        domain="biomedical",
    ),
    _doc(
        "bio:pcr",
        "Polymerase chain reaction amplification",
        [
            "PCR uses a thermostable DNA polymerase, typically Taq, to amplify a target DNA fragment.",
            "Thermal cycles of denaturation, annealing, and extension double the target each round in the exponential phase.",
        ],
        "synthetic-bio-016",
        domain="biomedical",
    ),
    _doc(
        "cs:syncret-baseline",
        "SyncRet: a lexical retrieval agent baseline",
        [
            "We introduce SyncRet, a ReAct agent that issues BM25 queries over a frozen abstract corpus.",
            "Training uses only the Standard-500k question set. No auxiliary web dumps are mixed in.",
            "Evaluation is reported on FullBench, the complete held-out split of 2000 questions.",
            "SyncRet attains 41.2% exact match on FullBench with a six-call exploration budget.",
        ],
        "synthetic-cs-001",
        domain="cs",
        year=2024,
    ),
    _doc(
        "cs:boostnet",
        "BoostNet: improving retrieval agents with extra data",
        [
            "BoostNet reports 45.4% exact match, a 4.2 point gain over the SyncRet number of 41.2%.",
            "The training mixture is Standard-500k plus ExtraMix-2M, a two-million-question synthesis dump.",
            "Numbers in the main table are measured on BoostSplit, an easy 800-question subset of FullBench.",
            "The authors do not report FullBench. Limitations note that ExtraMix-2M may overlap web quizzes.",
        ],
        "synthetic-cs-002",
        domain="cs",
        year=2024,
    ),
    _doc(
        "cs:grpo-lite",
        "GRPO-Lite: group size and context for retrieval RL",
        [
            "GRPO-Lite fine-tunes a 4B policy with group relative policy optimization.",
            "Each question samples four trajectories. The reference is the frozen base policy.",
            "The context window during rollout is 8192 tokens. Observation tokens are loss-masked.",
            "With four trajectories, all-fail groups produce zero advantage and are logged separately.",
        ],
        "synthetic-cs-003",
        domain="cs",
        year=2025,
    ),
    _doc(
        "cs:lora-rank",
        "LoRA rank ablation on a 4B retrieval policy",
        [
            "We attach LoRA adapters to attention projections of a 4B decoder.",
            "Rank 16 reaches 38.0% EM. Rank 64 reaches 38.4% EM on the same 200-question probe.",
            "Peak memory on one 80GB card is 46GB at rank 16 and 51GB at rank 64 with 8k context.",
            "The authors recommend rank 16 when the probe difference stays within 0.5 points.",
        ],
        "synthetic-cs-004",
        domain="cs",
        year=2025,
    ),
    _doc(
        "cs:dense-vs-bm25",
        "Dense retrievers are not free accuracy",
        [
            "Replacing BM25 with an e5 dense index lifts recall@3 from 0.61 to 0.70 on PaperDev.",
            "End-to-end agent EM moves from 40.1% to 41.0% under the same six-call budget.",
            "Index RAM for e5 on 16 million abstracts is reported as 64GB; BM25 stays under 12GB.",
            "The paper treats dense retrieval as an environment change, not a policy improvement.",
        ],
        "synthetic-cs-005",
        domain="cs",
        year=2025,
    ),
    _doc(
        "cs:async-lag",
        "Policy lag in asynchronous retrieval RL",
        [
            "An async actor-learner with a bound of two policy versions raises throughput 1.6x versus sync batches.",
            "When the lag bound is removed, exact match drops 2.1 points and discarded groups rise to 18%.",
            "The authors keep a group together on one policy version and drop incomplete groups.",
            "They advise against claiming async quality gains from token-per-second plots alone.",
        ],
        "synthetic-cs-006",
        domain="cs",
        year=2025,
    ),
    _doc(
        "cs:qasper-single",
        "Single-paper reading is not cross-paper research",
        [
            "QASPER questions target one paper PDF. Answering them does not require a multi-document index.",
            "We convert QASPER into a retrieval setting by mixing the gold paper with 20 distractor papers.",
            "Extractive F1 on the converted split is 4 points below the original full-text F1 of 33.2.",
            "The paper reports converted-retrieval F1 and original full-text F1 in separate tables.",
        ],
        "synthetic-cs-007",
        domain="cs",
        year=2023,
    ),
    _doc(
        "cs:negative-fullbench",
        "BoostNet on FullBench: a negative result",
        [
            "An independent re-run trains BoostNet on ExtraMix-2M and evaluates on FullBench rather than BoostSplit.",
            "FullBench exact match is 40.8%, within 0.4 points of SyncRet at 41.2%.",
            "The 4.2 point main-table gain is therefore not recovered on the original SyncRet split.",
            "The re-run keeps the six-call budget and the BM25 index unchanged.",
        ],
        "synthetic-cs-008",
        domain="cs",
        year=2025,
    ),
    _doc(
        "cs:contamination",
        "Quiz-dump overlap in ExtraMix-2M",
        [
            "String match finds 6.4% of ExtraMix-2M questions duplicated in public quiz dumps.",
            "After removing those items, BoostSplit EM falls from 45.4% to 42.1%.",
            "The authors release the overlap list and the filtered mixture hash.",
            "They do not claim ExtraMix-2M is contamination-free before filtering.",
        ],
        "synthetic-cs-009",
        domain="cs",
        year=2025,
    ),
    _doc(
        "cs:lr-schedule",
        "Constant versus cosine learning rates for GRPO-Lite",
        [
            "A constant 1e-6 LoRA learning rate is compared with cosine decay from 2e-6 to 1e-7.",
            "After 20 GRPO steps, cosine reaches 39.1% EM and constant reaches 38.7% on Probe-200.",
            "Both runs use group size 4 and start from the same base checkpoint.",
            "Variance across two seeds is 0.6 points, so the 0.4 point gap is not resolved.",
        ],
        "synthetic-cs-010",
        domain="cs",
        year=2025,
    ),
    _doc(
        "cs:tool-budget",
        "Accuracy versus exploration budget",
        [
            "The same base policy is evaluated at 2, 4, and 6 exploration calls.",
            "Exact match is 31.0% at 2 calls, 36.4% at 4 calls, and 38.1% at 6 calls on Probe-200.",
            "Mean search calls at the 6-call cap is 2.4. Additional calls mostly repeat failed queries.",
            "The authors plot EM against budget and do not collapse the three settings into one number.",
        ],
        "synthetic-cs-011",
        domain="cs",
        year=2025,
    ),
    _doc(
        "cs:sft-filter",
        "GRPO group logging for retrieval RL",
        [
            "GRPO groups are collected in the same harness used at deployment.",
            "A group is logged when every trajectory finishes under the tool budget.",
            "Of 800 sampled groups, 210 have mixed success. 40 of those include one failed search then recovery.",
            "Gold labels stay with the offline grader and are not shown to the policy.",
        ],
        "synthetic-cs-012",
        domain="cs",
        year=2025,
    ),
    _doc(
        "cs:distractor-optimizer",
        "A survey of SGD variants unrelated to retrieval agents",
        [
            "This survey reviews momentum, RMSProp, and Adam on convex quadratic objectives.",
            "No retrieval corpus, question set, or language-model agent is studied.",
            "Adam is described with default betas 0.9 and 0.999.",
        ],
        "synthetic-cs-d1",
        domain="cs",
        year=2018,
    ),
    _doc(
        "bio:distractor-glucose",
        "Dietary fiber and glycemic index",
        [
            "Soluble fiber slows glucose absorption and can lower postprandial glycemic peaks.",
            "The abstract does not mention insulin-producing cell types.",
        ],
        "synthetic-bio-d1",
        domain="biomedical",
    ),
    _doc(
        "bio:distractor-virus",
        "Influenza hemagglutinin antigenic drift",
        [
            "Seasonal influenza vaccines are updated because hemagglutinin accumulates antigenic drift.",
            "The abstract does not discuss coronavirus spike proteins or ACE2.",
        ],
        "synthetic-bio-d2",
        domain="biomedical",
    ),
    _doc(
        "missing:empty-methods",
        "Methods withheld in this snapshot",
        [
            "The public snapshot omits the hyperparameter table and the random seeds.",
            "Future work mentions a 70B run without reporting its exact match.",
        ],
        "synthetic-missing-001",
        domain="cs",
    ),
]


def _bio(task_id: str, question: str, answer: str, aliases: list[str], doc_id: str, category: str, hint: str) -> DevTask:
    para = f"{doc_id}:0"
    return DevTask(
        task_id=task_id,
        question=question,
        split="dev",
        search_hint=hint,
        spec=GradingSpec(
            task_id=task_id,
            answer=answer,
            aliases=tuple(aliases),
            gold_evidence_ids=(para,),
            support_doc_ids=(doc_id,),
            facts=(answer,),
            category=category,
            scoring="exact_match",
            answerable=True,
        ),
    )


def _cs(
    task_id: str,
    question: str,
    answer: str,
    aliases: list[str],
    evidence: list[str],
    docs: list[str],
    hint: str,
    category: str = "cs-conditions",
) -> DevTask:
    return DevTask(
        task_id=task_id,
        question=question,
        split="dev",
        search_hint=hint,
        spec=GradingSpec(
            task_id=task_id,
            answer=answer,
            aliases=tuple(aliases),
            gold_evidence_ids=tuple(evidence),
            support_doc_ids=tuple(docs),
            facts=(answer,),
            category=category,
            scoring="exact_match",
            answerable=True,
        ),
    )


TASKS: list[DevTask] = [
    _bio("bio-001", "Which gene is mutated in childhood retinoblastoma?", "RB1", ["Rb1", "RB1 gene"], "bio:rb1", "genetics", "childhood retinoblastoma RB1"),
    _bio("bio-002", "Which gene, when pathogenic, raises hereditary breast cancer risk in this corpus?", "BRCA1", ["BRCA1 gene"], "bio:brca1", "genetics", "BRCA1 hereditary breast cancer"),
    _bio("bio-003", "Which tyrosine kinase does imatinib inhibit in CML?", "BCR-ABL", ["BCR-ABL tyrosine kinase", "BCR ABL"], "bio:imatinib", "therapeutics", "imatinib BCR-ABL CML"),
    _bio("bio-004", "Which pancreatic cell type secretes insulin?", "beta cells", ["pancreatic beta cells", "beta cell"], "bio:insulin", "anatomy", "pancreatic beta cells insulin"),
    _bio("bio-005", "Which RNA-guided endonuclease from Streptococcus pyogenes is used in CRISPR editing here?", "Cas9", ["SpCas9", "Cas9 nuclease"], "bio:crispr", "methods", "Cas9 CRISPR Streptococcus pyogenes"),
    _bio("bio-006", "Which gene encodes the p53 transcription factor?", "TP53", ["TP53 gene", "p53 gene"], "bio:tp53", "genetics", "TP53 p53 tumor suppressor"),
    _bio("bio-007", "What is the recommended initial pharmacologic therapy for type 2 diabetes in this abstract?", "metformin", ["Metformin"], "bio:metformin", "therapeutics", "metformin first-line type 2 diabetes"),
    _bio("bio-008", "Which ligand does bevacizumab bind?", "VEGF-A", ["VEGFA", "VEGF A"], "bio:vegf", "therapeutics", "bevacizumab VEGF-A"),
    _bio("bio-009", "Which T-cell subset recognizes peptides on MHC class I?", "CD8 T cells", ["CD8-positive cytotoxic T cells", "CD8"], "bio:mhc1", "immunology", "MHC class I CD8 T cells"),
    _bio("bio-010", "Where is most ATP generated in aerobic eukaryotic cells according to this abstract?", "mitochondrial oxidative phosphorylation", ["mitochondria", "oxidative phosphorylation"], "bio:atp", "cell-biology", "mitochondrial oxidative phosphorylation ATP"),
    _bio("bio-011", "Which metal atom in heme binds oxygen in hemoglobin?", "iron", ["ferrous iron", "Fe"], "bio:hemoglobin", "physiology", "hemoglobin heme iron oxygen"),
    _bio("bio-012", "What does the presynaptic terminal release into the synaptic cleft?", "neurotransmitter vesicles", ["neurotransmitter", "vesicles"], "bio:synapse", "physiology", "chemical synapse neurotransmitter vesicles"),
    _bio("bio-013", "Which host receptor does the SARS-CoV-2 spike protein bind?", "ACE2", ["angiotensin-converting enzyme 2", "ACE2 receptor"], "bio:ace2", "pathogens", "SARS-CoV-2 ACE2 receptor"),
    _bio("bio-014", "Which peptide aggregates in neuritic plaques of Alzheimer disease here?", "amyloid-beta", ["amyloid beta", "A-beta", "amyloid-beta peptides"], "bio:amyloid", "disease", "Alzheimer amyloid-beta plaques"),
    _bio("bio-015", "Which midbrain structure loses dopaminergic neurons in Parkinson disease here?", "substantia nigra pars compacta", ["substantia nigra", "SNpc"], "bio:dopamine", "anatomy", "Parkinson substantia nigra dopamine"),
    _bio("bio-016", "Which thermostable polymerase is typically used in PCR in this abstract?", "Taq", ["Taq polymerase", "thermostable DNA polymerase"], "bio:pcr", "methods", "PCR Taq polymerase"),
    _cs(
        "cs-001",
        "What training set does SyncRet use?",
        "Standard-500k",
        ["Standard-500k question set", "only Standard-500k"],
        ["cs:syncret-baseline:1"],
        ["cs:syncret-baseline"],
        "SyncRet Standard-500k training",
        "cs-setup",
    ),
    _cs(
        "cs-002",
        "What exact match does SyncRet report on FullBench?",
        "41.2%",
        ["41.2", "41.2 percent"],
        ["cs:syncret-baseline:3"],
        ["cs:syncret-baseline"],
        "SyncRet FullBench exact match 41.2",
        "cs-setup",
    ),
    _cs(
        "cs-003",
        "Which extra dataset is mixed into BoostNet training besides Standard-500k?",
        "ExtraMix-2M",
        ["ExtraMix-2M synthesis dump"],
        ["cs:boostnet:1"],
        ["cs:boostnet"],
        "BoostNet ExtraMix-2M training mixture",
    ),
    _cs(
        "cs-004",
        "Which evaluation split is used in the BoostNet main table?",
        "BoostSplit",
        ["BoostSplit easy subset of FullBench"],
        ["cs:boostnet:2"],
        ["cs:boostnet"],
        "BoostNet BoostSplit evaluation",
    ),
    _cs(
        "cs-005",
        "Before reproducing SyncRet, does BoostNet's 4.2 point gain depend on extra training data or a different evaluation split?",
        "yes: ExtraMix-2M and BoostSplit",
        [
            "yes",
            "depends on ExtraMix-2M and BoostSplit",
            "extra data ExtraMix-2M and eval BoostSplit",
        ],
        ["cs:boostnet:1", "cs:boostnet:2", "cs:syncret-baseline:1", "cs:syncret-baseline:2"],
        ["cs:boostnet", "cs:syncret-baseline"],
        "BoostNet extra data BoostSplit versus SyncRet FullBench",
        "autotraining-demo",
    ),
    _cs(
        "cs-006",
        "How many trajectories per question does GRPO-Lite sample?",
        "4",
        ["four", "four trajectories"],
        ["cs:grpo-lite:1"],
        ["cs:grpo-lite"],
        "GRPO-Lite group size four trajectories",
        "cs-rl",
    ),
    _cs(
        "cs-007",
        "What rollout context length does GRPO-Lite use?",
        "8192 tokens",
        ["8192", "8k", "8k context"],
        ["cs:grpo-lite:2"],
        ["cs:grpo-lite"],
        "GRPO-Lite 8192 context window",
        "cs-rl",
    ),
    _cs(
        "cs-008",
        "Which LoRA rank does the 4B ablation recommend when the probe gap is within 0.5 points?",
        "16",
        ["rank 16", "LoRA rank 16"],
        ["cs:lora-rank:3"],
        ["cs:lora-rank"],
        "LoRA rank 16 recommendation",
        "cs-training",
    ),
    _cs(
        "cs-009",
        "Does replacing BM25 with e5 count as a policy improvement in Dense vs BM25?",
        "no",
        ["environment change", "not a policy improvement"],
        ["cs:dense-vs-bm25:3"],
        ["cs:dense-vs-bm25"],
        "dense retrieval environment change not policy",
        "cs-eval",
    ),
    _cs(
        "cs-010",
        "What happens to exact match when the async lag bound is removed?",
        "drops 2.1 points",
        ["drops 2.1", "2.1 points drop", "-2.1"],
        ["cs:async-lag:1"],
        ["cs:async-lag"],
        "async RL lag bound exact match drop",
        "cs-rl",
    ),
    _cs(
        "cs-011",
        "What FullBench exact match does the BoostNet re-run report?",
        "40.8%",
        ["40.8", "40.8 percent"],
        ["cs:negative-fullbench:1"],
        ["cs:negative-fullbench"],
        "BoostNet FullBench negative result 40.8",
        "cs-negative",
    ),
    _cs(
        "cs-012",
        "After removing quiz-dump overlap, what BoostSplit EM remains?",
        "42.1%",
        ["42.1", "42.1 percent"],
        ["cs:contamination:1"],
        ["cs:contamination"],
        "ExtraMix-2M contamination filtered 42.1",
        "cs-data",
    ),
    DevTask(
        task_id="na-001",
        question="What exact match did the withheld 70B run achieve?",
        split="dev",
        search_hint="70B run exact match withheld",
        spec=GradingSpec(
            task_id="na-001",
            answer="unknown",
            aliases=("n/a", "cannot answer", "insufficient evidence"),
            gold_evidence_ids=("missing:empty-methods:1",),
            support_doc_ids=("missing:empty-methods",),
            facts=(),
            category="unanswerable",
            scoring="exact_match",
            answerable=False,
            notes="The snapshot never states a 70B EM number.",
        ),
    ),
    DevTask(
        task_id="na-002",
        question="Which random seeds were used for the withheld hyperparameter table?",
        split="dev",
        search_hint="random seeds withheld hyperparameter table",
        spec=GradingSpec(
            task_id="na-002",
            answer="unknown",
            aliases=("n/a", "cannot answer", "insufficient evidence"),
            gold_evidence_ids=("missing:empty-methods:0",),
            support_doc_ids=("missing:empty-methods",),
            facts=(),
            category="unanswerable",
            scoring="exact_match",
            answerable=False,
        ),
    ),
    DevTask(
        task_id="na-003",
        question="What is the best retrieval agent in this corpus?",
        split="dev",
        search_hint="best retrieval agent ranking",
        spec=GradingSpec(
            task_id="na-003",
            answer="unknown",
            aliases=("n/a", "cannot answer", "insufficient evidence"),
            gold_evidence_ids=(),
            support_doc_ids=(),
            facts=(),
            category="unanswerable",
            scoring="exact_match",
            answerable=False,
            notes="No paper defines a single best agent across matched settings.",
        ),
    ),
    DevTask(
        task_id="na-004",
        question="Which influenza vaccine strain does ACE2 bind?",
        split="dev",
        search_hint="influenza vaccine ACE2 bind",
        spec=GradingSpec(
            task_id="na-004",
            answer="unknown",
            aliases=("n/a", "cannot answer", "insufficient evidence"),
            gold_evidence_ids=(),
            support_doc_ids=("bio:ace2", "bio:distractor-virus"),
            facts=(),
            category="unanswerable",
            scoring="exact_match",
            answerable=False,
            notes="ACE2 is discussed for SARS-CoV-2, not influenza vaccine strains.",
        ),
    ),
]


def public_task_record(task: DevTask) -> dict:
    return {
        "task_id": task.task_id,
        "question": task.question,
        "split": task.split,
        "environment_id": "synthetic-dev",
        "category": task.spec.category,
    }


def grading_record(task: DevTask) -> dict:
    spec = task.spec
    return {
        "task_id": spec.task_id,
        "answer": spec.answer,
        "aliases": list(spec.aliases),
        "gold_evidence_ids": list(spec.gold_evidence_ids),
        "support_doc_ids": list(spec.support_doc_ids),
        "facts": list(spec.facts),
        "category": spec.category,
        "scoring": spec.scoring,
        "answerable": spec.answerable,
        "notes": spec.notes,
        "search_hint": task.search_hint,
    }


def iter_public_tasks() -> list[dict]:
    return [public_task_record(task) for task in TASKS]


def iter_grading() -> list[dict]:
    return [grading_record(task) for task in TASKS]


def task_by_id() -> dict[str, DevTask]:
    return {task.task_id: task for task in TASKS}
